[client]
# 隐藏部分按钮
showErrorDetails = false
showSidebarNavigation = true

[logger]
level = "warning"

[browser]
gatherUsageStats = false
serverAddress = "localhost"

[theme]
# 使用自定义主题，避免用户手动切换
base = "dark"
primaryColor = "#68d3ff"
backgroundColor = "#0f0f1e"
secondaryBackgroundColor = "#1a1a3e"
textColor = "#e0e0e0"
font = "sans serif"
